apache/mynewt-artifact

image/create.go, image/image.go, sec/pkcs.go, sec/sign.go, sec/util.go
This is almost a straight copy of code from the newt repo, written by utzig@apache.org.
=>  Add support for ed25519 encrypted signing keys 

image/verify.go, mfg/mfg.go, mfg/verify.go
Prior to this commit, the `"mfg".Mfg.VerifyManifest()` function attempted to verify all of an mfg's embedded images.  This resulted in a clunky and unfriendly API:
* The caller was required to pass in a set of public signing keys and private encryption keys.
* There was no way to verify the manifest without also checking the embedded images.  E.g., if the caller doesn't have access to encryption keys, this function would fail even if the mfgimage is correct.
Now `VerifyManifest()` does not verify the embedded images.  To verify the embedded images, the caller should call `"mfg".Mfg.ExtractImages()` and call the image verification functions on each image separately.
=> mfg: Verify embedded images separately

image/image.go
This pulls in alvarop's change to newt:
> The correct flag for IMAGE_F_NON_BOOTABLE should be 0x10 instead of 0x02
> according to the mcuboot files:
> https://github.com/JuulLabs-OSS/mcuboot/blob/3c469bc698a9767859ed73cd0201c44161204d5c/boot/bootutil/include/bootutil/image.h#L46
Since this code is moving from `newt` to `artifact`, this commit needs to be pulled in.
=> Fix IMAGE_F_NON_BOOTABLE definition to match mcuboot

sec/pkcs.go, sec/sign.go
1) When using ec256 (aka secp256r1), passes the correct type to the marshalling function.
2) Update to use the standard library for parse the ed25519 PKCS#8 (must upgrade to go 1.13 or higher)
=> Fix signing with elliptic curves

image/create.go, image/image.go, sec/encrypt.go
This patch adds the necessary changes to support AES-256-CTR and hw key
encryption.  In addition, header and image padding have been added to
satisfy the hardware restrictions of being 1KB aligned for the encrypted
payload.
Added required TLVs for AES nonce and hw encryption key index.
Signed-off-by: Andy Gross <andy.gross@juul.com>
=> Add AES-256-CTR capabilities and dependencies

manifest/mfg_manifest.go
Add a new field to the `target` and `raw` mfg manifest items: `extra_manifest`.  This field is a generic map that gets passed through from the mfg definition.  This field is useful if the user needs to convey additional information to some system that knows how to parse a manufacturing manifest file.
=> New mfg manifest fields: target.extra, raw.extra

image/map.go, image/parse.go
Prior to this commit, when parsing an image that had protected TLVs:
* The protected TLVs were interpreted as normal TLVs.
* The normal TLVs were ignored.
=> Parse protected TLVs when parsing an image

image/create.go, image/image.go, sec/encrypt.go
This adds support for encrypting images using ECIES-P256. The MCUBoot
implementation was described here: https://github.com/JuulLabs-OSS/mcuboot/blob/master/docs/encrypted_images.md#ecies-p256-encryption
This only adds the infrastructure required by `newt` to create encrypted images. `imgmod` dependencies were not added.
=> Add support for image encryption using ECIES-P256

manifest/mfg_manifest.go
Allow an mfgimage manifest to indicate the names of the BSP's flash devices.
=> mfg_manifest: Add list of flash device names

image/image.go
The `Image#FindProtTlv` functions were returning TLVs from the regular list, not the protected list!
=> Fix FindProtTlv functions: were returning reg TLVs

image/parse.go
The ParseImage function was ignoring header padding.  For images with header padding, this function truncated the image.
=> image: During parsing, account for header padding

image/verify.go
Before this PR, the image verification procedure would fail early if decryption failed.  The procedure is supposed to try all the keys and report success if any of them works.
=> image: Try ALL enc keys when verifying hash

image/parse.go
When parsing an image file, if the image indicates an extra-long header, build a slice of bytes to hold the extra leading padding.  This is needed to perform the image hash calculation correctly.
=> image: calculate padding when parsing image

manifest/mfg_manifest.go
This field indicates the size of the target binary (either .bin or .img file).  This is useful for splitting an mfgimage into its constituent parts.  Without this change, the only method of doing this is to use a heuristic: remove all 0xff bytes from the end of each part (this is what `imgmod mfg split` does).  However, this leads to problems if a target or raw entry happens to contain trailing 0xff bytes.
=> manifest: Add `MfgManifestTarget.Size` field

image/create.go, image/image.go, image/verify.go, manifest/mfg_manifest.go
"Hardware-encrypted images" are images that run on devices capable of on-the-fly decryption.  These images differ from regular encrypted images in the following ways: 
* Contain some extra TLVs (nonce, secret ID)
* The hash is of the *encrypted* image
=> Functions to decrypt hw-encrypted images

manifest/mfg_manifest.go
This function was broken due to a typo in a comparison.
=> FindWithinFlashAreaDevOff: Fix bad compare

sec/encrypt.go
If the caller of EncryptAES() supplied a nonce shorter than 16 bytes, the function would enter an endless loop.
=> sec: Fix infinite loop

image/create.go, image/image.go
This patch adds a legacy TLV option for using the legacy values for AES_NONCE
and SECRET_ID.  This allows newer newt tools to build usable application images
for systems which cannot support the new TLVs on boot.
Signed-off-by: Andy Gross <andy.gross@juul.com>
=> image: Support legacy TLV values via option

image/create.go
Old MCUboot releases required the ASN1 of ec256 signatures to be padded; this was removed with:
https://github.com/mcu-tools/mcuboot/pull/680
After this change, it is possible to build EC-256 based signature validation using Mbed TLS. This commit removes the padding and should allow following releases to use Mbed TLS, instead of Tinycrypt.
Related to https://github.com/apache/mynewt-newt/issues/450
=> Remove ec256 ASN1 signature padding

.github/workflows/build.yml
ASF moved away from Travis to Github Actions.
=> Integration with Github Actions
